### ISSUE TITLE
Paddle A not working properly

### ISSUE THREAD

**Issue by iamjayshree** [IamJayshree/Pong#1]

**Comment by shepherdjay** [comment]
I'm interested in giving you a hand on this. However can you clarify - I ran your program and the A paddle does seem to work.

**Comment by iamjayshree** [comment]
> I'm interested in giving you a hand on this. However can you clarify - I ran your program and the A paddle does seem to work.

Hello actually the ball passes one of the paddle, try and run the game again, the paddle's job is to stop the ball, but it doesn't

**Comment by iamjayshree** [comment]
I received a PR, this issue is actually fixed :)
